In [1]:
import pandas as pd
routes=pd.read_csv("routes.csv")

In [2]:
x=input("enter starting station :")

enter starting station :Hari Nagar Clock Tower

In [3]:
import numpy as np

In [4]:
routes.head()

   route_short_name route_long_name  route_type  route_id
0               NaN         108DOWN           3         0
1               NaN      108STLDOWN           3         1
2               NaN        108STLUp           3         2
3               NaN           108UP           3         3
4               NaN         185DOWN           3         4

In [5]:
routes=routes[['route_long_name','route_id']].values

In [6]:
routes

array([['108DOWN', 0],
       ['108STLDOWN', 1],
       ['108STLUp', 2],
       ...,
       ['727UP', 540],
       ['751Down', 541],
       ['751Up', 542]], dtype=object)

In [7]:
stops=pd.read_csv("stops.csv")

In [8]:
stops.head()

   stop_id stop_code                       stop_name   stop_lat   stop_lon
0        0    U01761  Adarsh Nagar / Bharola Village  28.715917  77.170867
1        1    DC4248          British High Comission  28.598533  77.191383
2        2    U02398                     Azad Market  28.664700  77.208400
3        3    U02416                    Kidwai Nagar  28.575700  77.209700
4        4    DC4271                   Rashid Market  28.650200  77.278667

In [9]:
start_point=stops[stops.stop_name==x]

In [10]:
end_point=stops[stops.stop_name=='Moti Nagar']

In [11]:
stops=stops[['stop_id','stop_name']].values

In [12]:
np.shape(stops)

(3465, 2)

In [13]:
bus_start_id=start_point.stop_id.values

In [14]:
bus_start_id

array([2270])

In [15]:
end_point.head()

      stop_id stop_code   stop_name   stop_lat   stop_lon
552       554    U01424  Moti Nagar  28.658615  77.144108
1794     1837    U01425  Moti Nagar  28.658867  77.144183

In [16]:
bus_stop_id=end_point['stop_id'].values

In [17]:
bus_stop_id

array([ 554, 1837])

In [18]:
bus_stop=pd.read_csv("stop_times.csv")

In [19]:
bus_stop.head()

    trip_id arrival_time departure_time  stop_id  stop_sequence
0         0     15:48:00       15:48:00     2270              0
1         0     15:49:52       15:49:52      978              1
2         0     15:52:17       15:52:17     3005              2
3         0     15:54:02       15:54:02      255              3
4         0     15:56:47       15:56:47     3074              4
5         0     15:59:32       15:59:32      764              5
6         0     16:02:49       16:02:49      619              6
7         0     16:04:22       16:04:22     1973              7
8         0     16:07:54       16:07:54     2502              8
9         0     16:14:25       16:14:25     2871              9
10        0     16:17:29       16:17:29     3039             10
11        0     16:20:53       16:20:53     1462             11
12        0     16:24:01       16:24:01      731             12
13        0     16:26:04       16:26:04     1837             13
14        0     16:28:15       16:28:15     3585             14
15        0     16:32:08       16:32:08     3425             15
16        0     16:36:17       16:36:17     3227             16
17        0     16:39:23       16:39:23      949             17
18        0     16:42:13       16:42:13      953             18
19        0     16:45:45       16:45:45     3092             19
20        0     16:47:35       16:47:35      803             20
21        0     16:50:30       16:50:30     1416             21
22        0     16:52:20       16:52:20     2768             22
23        0     16:54:13       16:54:13     3034             23
24        0     16:55:59       16:55:59      733             24
25        0     16:57:20       16:57:20      703             25
26        0     17:02:11       17:02:11      580             26
27        0     17:06:37       17:06:37     3156             27
28        0     17:07:33       17:07:33     2142             28
29        0     17:09:05       17:09:05     3451             29
30        0     17:10:18       17:10:18      502             30
31        0     17:10:58       17:10:58      341             31
32        0     17:13:16       17:13:16     2809             32
33        0     17:15:11       17:15:11     1653             33
34        0     17:16:55       17:16:55     2945             34
35        0     17:18:51       17:18:51      181             35
36        0     17:19:32       17:19:32     1472             36
37        0     17:23:13       17:23:13     2771             37
38        0     17:25:10       17:25:10      453             38
39        0     17:26:55       17:26:55     3054             39
40        0     17:28:10       17:28:10       52             40
41        0     17:28:49       17:28:49     2035             41
42        0     17:30:45       17:30:45     1025             42
43        0     17:33:36       17:33:36     3195             43
44        1     16:12:00       16:12:00     2270              0

In [20]:
bus_stop=bus_stop[['trip_id','stop_id']].values

In [21]:
np.shape(bus_stop)

(674909, 2)

In [22]:
trips=pd.read_csv("trips.csv")

In [23]:
trips.head()

   route_id  service_id  trip_id
0         0           1        0
1         0           1        1
2         0           1        2
3         0           1        3
4         0           1        4

In [24]:
trips=trips[['route_id','trip_id']].values

In [25]:
trips

array([[    0,     0],
       [    0,     1],
       [    0,     2],
       ...,
       [  542, 16559],
       [  542, 16560],
       [  542, 16561]])

In [26]:
flag=0
x=0
y=0
cnt=0
z=555
k=0
for i in range(674909):
    if(bus_stop[i][1]==bus_start_id[0]):
        x=i
        for j in range (x+1,674909):
            if(bus_stop[j][1]==bus_stop_id[1]):
                y=j
                if(bus_stop[x][0]==bus_stop[y][0]):
                    flag=1
                    break
        if(cnt>=25):
            break
            
        if(flag==1):
            if(z==trips[i][0]):
                continue
            else:
                z=trips[i][0]
                print("---------------------")
                print("for bus",routes[trips[i][0]][0])
                print("------------------------------------------")
                cnt=cnt+1
                for w in range(x,y+1):
                    for m in range(3465):
                        if(stops[m][0]==bus_stop[w][1]):
                            print(stops[m][1])
                            break
       
if(flag==0):
    print("there is no direct route!")

---------------------
for bus 108DOWN
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 108STLDOWN
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 108UP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 185LnkSTLDown
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 185UP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 262LinkSTLDown
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 78DOWN
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 78STLUP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 78UP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 7LnkSTLUp
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 813CLDown
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 813CLUP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 937ADOWN
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 937AUP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 185LSTL2Down
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 185LSTLDown
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 206ADown
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 206AUp
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 211DOWN
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 211UP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 253DOWN
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 253UP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 258DOWN
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 258STLUp
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar
---------------------
for bus 258UP
------------------------------------------
Hari Nagar Clock Tower
DDU Hospital
Beriwala Bagh
Swarg Ashram
LIG Flats
Hari Nagar (Mohan Mandir) Mayapuri
Government Press
Mayapuri Depot
Wood Market
PS Kirti Nagar
F Block Kirti Nagar
Kirti Nagar
Moti Nagar Market
Moti Nagar